"""Alembic environment -- async, and sharing the application's own config.

Two choices worth naming:

* The URL comes from `Settings`, not from alembic.ini. There is one place that
  knows where the database is.
* The engine is async, using the same asyncpg driver the app uses. The
  alternative is a second sync driver (psycopg) installed purely for
  migrations -- a dependency, a second connection code path, and a second way
  for TLS or pooling behaviour to differ from production.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import Connection, pool
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.core.config import get_settings
from app.db.base import Base

# Importing the models module is what populates Base.metadata; without it,
# autogenerate would cheerfully emit a migration dropping every table.
from app.db import models  # noqa: F401  isort:skip

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = Base.metadata


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Detect column type changes, not just added/dropped columns.
        compare_type=True,
        compare_server_default=True,
        # Emit constraint names using the metadata naming convention so
        # autogenerated downgrades can actually find what to drop.
        render_as_batch=False,
        include_schemas=False,
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of executing it (`alembic upgrade head --sql`).

    This is how migrations get reviewed before they touch a production
    database, and how they get handed to a DBA who runs them out of band.
    """
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # migrations are short-lived; pooling is noise
    )
    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
