"""Declarative base and shared column conventions."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, ClassVar

from sqlalchemy import DateTime, MetaData, Uuid, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic constraint and index names. Without this, Postgres invents
# names, Alembic autogenerate cannot match them across revisions, and dropping
# a constraint in a later migration means looking it up by hand in psql.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    # Map Python annotations to Postgres types once, so every model gets
    # timezone-aware timestamps and real JSONB without repeating itself.
    type_annotation_map: ClassVar[dict[Any, Any]] = {
        datetime: DateTime(timezone=True),
        uuid.UUID: Uuid(as_uuid=True),
        dict[str, Any]: JSONB,
    }


def uuid_pk() -> Mapped[uuid.UUID]:
    """Primary key generated by the application, not the database.

    Application-side generation is what allows an id to be known before the row
    exists -- which is exactly what makes at-least-once ingestion idempotent
    (`ON CONFLICT (id) DO NOTHING`) rather than duplicate-producing.
    """
    return mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """`created_at` / `updated_at` maintained by the database clock.

    Server-side defaults rather than Python ones: a single clock (Postgres')
    orders the rows, so multiple API replicas with drifting clocks cannot
    produce a nonsensical timeline.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
