"""Persistence model.

Four tables, two concerns:

* `conversations` + `messages` -- the product. What the user said and what the
  assistant said back.
* `inference_logs` + `events_raw` -- the observability record. One row per LLM
  call, plus the untouched event it was derived from.

The two halves are deliberately loosely coupled: an inference log survives the
deletion of the message it produced, because the operational record of "we
spent 1,400 tokens and 2.3 seconds on this call" outlives the transcript.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum as PyEnum
from typing import Any

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, uuid_pk
from app.domain.enums import (
    ConversationStatus,
    InferenceStatus,
    MessageRole,
    ProcessingStatus,
)


def _enum(python_enum: type[PyEnum], name: str) -> Enum:
    """Store enums as VARCHAR + CHECK rather than a native Postgres ENUM type.

    Native enums require an `ALTER TYPE` (historically non-transactional, and
    still awkward to reverse) every time a value is added. A check constraint
    is a plain, reversible DDL change and reads identically in queries.

    Two non-default options, both load-bearing:

    * `values_callable` -- SQLAlchemy persists enum *names* by default, which
      would put `'ERROR'` in a column whose documented domain is `'error'`.
      Every hand-written dashboard query and every JSON payload would then
      have to know about the discrepancy. Persist the values.
    * `create_constraint` -- defaults to False in SQLAlchemy 2.0, meaning
      `native_enum=False` alone yields an unconstrained VARCHAR. Without this
      the database would accept any string at all.
    """
    return Enum(
        python_enum,
        name=name,
        native_enum=False,
        length=32,
        validate_strings=True,
        create_constraint=True,
        values_callable=lambda enum_cls: [member.value for member in enum_cls],
    )


class Conversation(Base, TimestampMixin):
    __tablename__ = "conversations"

    id: Mapped[uuid.UUID] = uuid_pk()
    title: Mapped[str | None] = mapped_column(Text, default=None)
    status: Mapped[ConversationStatus] = mapped_column(
        _enum(ConversationStatus, "conversation_status"),
        default=ConversationStatus.ACTIVE,
        nullable=False,
    )

    messages: Mapped[list[Message]] = relationship(
        back_populates="conversation",
        cascade="all, delete-orphan",
        order_by="Message.seq",
        lazy="selectin",
    )

    __table_args__ = (
        # The conversation list is sorted by recency and paged; this is the
        # index that keeps it from degrading into a full scan plus sort.
        Index("ix_conversations_updated_at", "updated_at", postgresql_using="btree"),
    )


class Message(Base):
    __tablename__ = "messages"

    id: Mapped[uuid.UUID] = uuid_pk()
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False
    )
    role: Mapped[MessageRole] = mapped_column(_enum(MessageRole, "message_role"), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)

    #: Explicit per-conversation ordering. Timestamps are the wrong tool here:
    #: two messages written in the same millisecond, or written by replicas
    #: with skewed clocks, would order non-deterministically. An integer
    #: sequence is boring and always right.
    seq: Mapped[int] = mapped_column(Integer, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    conversation: Mapped[Conversation] = relationship(back_populates="messages")

    __table_args__ = (
        # Enforces the ordering invariant in the database rather than trusting
        # every future caller to get it right.
        UniqueConstraint("conversation_id", "seq", name="uq_messages_conversation_id_seq"),
        Index("ix_messages_conversation_id_seq", "conversation_id", "seq"),
    )


class InferenceLog(Base):
    """One row per LLM call -- the core deliverable of this system.

    Written by the ingestion worker, never by the request path.
    """

    __tablename__ = "inference_logs"

    #: Generated by the instrumentation wrapper before the call is made, so
    #: redelivery from the event stream collides on the primary key instead of
    #: inserting a duplicate. This is what makes at-least-once delivery safe.
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)

    #: Version of the event contract this row was parsed from. Lets the
    #: replay path handle historical payload shapes explicitly.
    schema_version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    # --- Association (nullable by design) ----------------------------------
    #: ON DELETE SET NULL, not CASCADE: deleting a conversation removes the
    #: transcript but must not erase the record of the spend and latency it
    #: incurred.
    conversation_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("conversations.id", ondelete="SET NULL"), default=None
    )
    #: Null whenever the call produced no assistant message -- every error and
    #: every cancellation. Those are precisely the rows the dashboards exist
    #: to surface, so this must not be NOT NULL.
    message_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("messages.id", ondelete="SET NULL"), default=None
    )

    # --- What ran ----------------------------------------------------------
    #: Intentionally unconstrained: adding a provider is a config change, not
    #: a schema migration.
    provider: Mapped[str] = mapped_column(String(64), nullable=False)
    model: Mapped[str] = mapped_column(String(128), nullable=False)
    status: Mapped[InferenceStatus] = mapped_column(
        _enum(InferenceStatus, "inference_status"), nullable=False
    )
    streamed: Mapped[bool] = mapped_column(nullable=False, default=False)

    # --- Timing ------------------------------------------------------------
    #: When the call actually happened, measured in the request path. Distinct
    #: from `ingested_at`, which is when this row was written -- they can be
    #: far apart when the worker is catching up, and every dashboard must
    #: bucket by the former or a backlog looks like a traffic spike.
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    completed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    latency_ms: Mapped[int | None] = mapped_column(Integer, default=None)
    #: Time to first token. Null for non-streaming calls and for streaming
    #: calls that failed before emitting anything.
    ttft_ms: Mapped[int | None] = mapped_column(Integer, default=None)

    # --- Cost ---------------------------------------------------------------
    input_tokens: Mapped[int | None] = mapped_column(Integer, default=None)
    output_tokens: Mapped[int | None] = mapped_column(Integer, default=None)

    # --- Content (truncated + redacted before it ever reaches this table) ---
    input_preview: Mapped[str | None] = mapped_column(Text, default=None)
    output_preview: Mapped[str | None] = mapped_column(Text, default=None)

    # --- Failure ------------------------------------------------------------
    error_type: Mapped[str | None] = mapped_column(String(128), default=None)
    error_message: Mapped[str | None] = mapped_column(Text, default=None)
    finish_reason: Mapped[str | None] = mapped_column(String(64), default=None)

    #: Escape hatch for provider-specific fields that are worth keeping but not
    #: worth a column: vendor request ids, cache-hit counters, safety verdicts.
    #: Adding a provider therefore needs no migration.
    raw_metadata: Mapped[dict[str, Any] | None] = mapped_column(default=None)

    __table_args__ = (
        # Time-range scans: the shape of essentially every dashboard query.
        Index("ix_inference_logs_started_at", started_at.desc()),
        # Group-by provider/model within a time range.
        Index("ix_inference_logs_provider_model_started_at", "provider", "model", "started_at"),
        # Partial index: the errors view reads a small slice of a large table,
        # so indexing only the failures keeps it cheap to maintain.
        Index(
            "ix_inference_logs_errors",
            "started_at",
            postgresql_where=(status == InferenceStatus.ERROR),
        ),
        Index("ix_inference_logs_conversation_id", "conversation_id"),
        # Non-negative durations and token counts. Cheap insurance against a
        # unit bug (seconds written into a milliseconds column) silently
        # poisoning every percentile on the dashboard.
        CheckConstraint("latency_ms IS NULL OR latency_ms >= 0", name="latency_non_negative"),
        CheckConstraint("ttft_ms IS NULL OR ttft_ms >= 0", name="ttft_non_negative"),
        CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0", name="input_tokens_non_negative"
        ),
        CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0", name="output_tokens_non_negative"
        ),
        CheckConstraint("completed_at >= started_at", name="completed_after_started"),
    )


class RawEvent(Base):
    """Append-only landing zone for every event the worker receives.

    Costs roughly double the storage of `inference_logs` alone. What it buys is
    replay: if the parsing logic ships a bug, the fix can be re-applied to the
    original payloads instead of leaving permanently wrong rows behind. At this
    volume that is a good trade; at massive volume it would need a retention
    policy attached.
    """

    __tablename__ = "events_raw"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(nullable=False)

    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    processed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    processing_status: Mapped[ProcessingStatus] = mapped_column(
        _enum(ProcessingStatus, "processing_status"),
        nullable=False,
        default=ProcessingStatus.PENDING,
    )
    #: Why parsing failed, for the failed-event triage query.
    processing_error: Mapped[str | None] = mapped_column(Text, default=None)

    __table_args__ = (
        # "Show me what is stuck or broken" -- partial, because the healthy
        # majority of rows never need to be found this way.
        Index(
            "ix_events_raw_unprocessed",
            "received_at",
            postgresql_where=(processing_status != ProcessingStatus.PROCESSED),
        ),
    )
