"""initial schema

Revision ID: b1f45bfdfc2c
Revises:
Created: 2026-08-17 06:27:20.522085
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b1f45bfdfc2c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "cancelled",
                "archived",
                name="conversation_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        "ix_conversations_updated_at",
        "conversations",
        ["updated_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "events_raw",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "pending",
                "processed",
                "failed",
                name="processing_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events_raw")),
    )
    op.create_index(
        "ix_events_raw_unprocessed",
        "events_raw",
        ["received_at"],
        unique=False,
        postgresql_where=sa.text("processing_status != 'processed'"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "user",
                "assistant",
                "system",
                name="message_role",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("conversation_id", "seq", name="uq_messages_conversation_id_seq"),
    )
    op.create_index(
        "ix_messages_conversation_id_seq", "messages", ["conversation_id", "seq"], unique=False
    )
    op.create_table(
        "inference_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "success",
                "error",
                "cancelled",
                name="inference_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("streamed", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("input_preview", sa.Text(), nullable=True),
        sa.Column("output_preview", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("finish_reason", sa.String(length=64), nullable=True),
        sa.Column("raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "completed_at >= started_at", name=op.f("ck_inference_logs_completed_after_started")
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name=op.f("ck_inference_logs_input_tokens_non_negative"),
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0",
            name=op.f("ck_inference_logs_latency_non_negative"),
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name=op.f("ck_inference_logs_output_tokens_non_negative"),
        ),
        sa.CheckConstraint(
            "ttft_ms IS NULL OR ttft_ms >= 0", name=op.f("ck_inference_logs_ttft_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_inference_logs_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_inference_logs_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inference_logs")),
    )
    op.create_index(
        "ix_inference_logs_conversation_id", "inference_logs", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_inference_logs_errors",
        "inference_logs",
        ["started_at"],
        unique=False,
        postgresql_where=sa.text("status = 'error'"),
    )
    op.create_index(
        "ix_inference_logs_provider_model_started_at",
        "inference_logs",
        ["provider", "model", "started_at"],
        unique=False,
    )
    op.create_index(
        "ix_inference_logs_started_at",
        "inference_logs",
        [sa.literal_column("started_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inference_logs_started_at", table_name="inference_logs")
    op.drop_index("ix_inference_logs_provider_model_started_at", table_name="inference_logs")
    op.drop_index(
        "ix_inference_logs_errors",
        table_name="inference_logs",
        postgresql_where=sa.text("status = 'error'"),
    )
    op.drop_index("ix_inference_logs_conversation_id", table_name="inference_logs")
    op.drop_table("inference_logs")
    op.drop_index("ix_messages_conversation_id_seq", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "ix_events_raw_unprocessed",
        table_name="events_raw",
        postgresql_where=sa.text("processing_status != 'processed'"),
    )
    op.drop_table("events_raw")
    op.drop_index(
        "ix_conversations_updated_at", table_name="conversations", postgresql_using="btree"
    )
    op.drop_table("conversations")
    # ### end Alembic commands ###
